name: Compile with SourceMod

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.12.x", "1.13.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugins
        run: |
          for file in $(find -type f -name "*.sp")
          do
            echo -e "\nCompiling $file..."
            spcomp64 -v2 -i "${{ github.workspace }}/include" "$file"
          done
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Upload Compiled Plugins
        uses: actions/upload-artifact@v4
        with:
          name: plugins-${{ matrix.SM_VERSION }}
          path: ./**/*.smx
